spring.application.name=SpringBootPractice
spring.datasource.url=jdbc:postgresql://localhost:5432/springbootpractice
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
server.port=8081